version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - run:
          name: alioth
          command: |
            apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git zip python python3 flex cpio libncurses5-dev wget
            git clone https://github.com/UtsavBalar1231/Drone-scripts.git --depth=1 -b kona script && cd script
            bash setup-drone --aosp-clang
            bash build-kernel --aosp-clang
          no_output_timeout : 5h

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
